server:
  port: 8137
spring:
  application:
    name: newbee-cloud-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: goods-service-route
          uri: lb://newbee-cloud-goods-service
          order: 1
          predicates:
            - Path=/goods
            - Query=goodsId,^\+?[1-9][0-9]*$
        - id: goods-service-route2
          uri: lb://newbee-cloud-goods-service
          order: 0
          predicates:
            - Path=/goods/page/**
            - Method=POST



