server:
  port: 8161

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_distribution_goods_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: newbee-cloud-goods-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos
seata:
  enabled: true
  # 三个不同的服务命名为不同的名称
  application-id: goods-server
  # 事务分组配置
  tx-service-group: test_save_order_group
  service:
    vgroup-mapping:
      test_save_order_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:17748
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      cluster: default
