server:
  port: 8092

spring:
  application:
    name: newbee-cloud-shopcart-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos