server:
  port: 8154

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_distribution_cart_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: newbee-cloud-shopcart-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos