server:
  port: 8093

spring:
  application:
    name: newbee-cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos