server:
  port: 8129
spring:
  application:
    name: newbee-cloud-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true # ????????
          lower-case-service-id: true # ?????????
      routes:
        - id: goods-service-route
          uri: lb://newbee-cloud-goods-service
          order: 1
          predicates:
            - Path=/goods/**
        - id: shopcart-service-route
          uri: lb://newbee-cloud-shopcart-service
          order: 1
          predicates:
            - Path=/shop-cart/**

